spring:
  datasource:
    url: jdbc:mysql://localhost:3306/MicroservicesFinal?useSSL=false&allowPublicKeyRetrieval=true
    username: devuser
    password: devpass
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
