package com.example.demo.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class AlumnoProfileAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAlumnoProfileAllPropertiesEquals(AlumnoProfile expected, AlumnoProfile actual) {
        assertAlumnoProfileAutoGeneratedPropertiesEquals(expected, actual);
        assertAlumnoProfileAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAlumnoProfileAllUpdatablePropertiesEquals(AlumnoProfile expected, AlumnoProfile actual) {
        assertAlumnoProfileUpdatableFieldsEquals(expected, actual);
        assertAlumnoProfileUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAlumnoProfileAutoGeneratedPropertiesEquals(AlumnoProfile expected, AlumnoProfile actual) {
        assertThat(actual)
            .as("Verify AlumnoProfile auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAlumnoProfileUpdatableFieldsEquals(AlumnoProfile expected, AlumnoProfile actual) {
        assertThat(actual)
            .as("Verify AlumnoProfile relevant properties")
            .satisfies(a -> assertThat(a.getNombreAlumno()).as("check nombreAlumno").isEqualTo(expected.getNombreAlumno()))
            .satisfies(a ->
                assertThat(a.getDescripcionProyecto()).as("check descripcionProyecto").isEqualTo(expected.getDescripcionProyecto())
            );
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAlumnoProfileUpdatableRelationshipsEquals(AlumnoProfile expected, AlumnoProfile actual) {
        // empty method
    }
}
