package com.example.demo.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class EventoTipoAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEventoTipoAllPropertiesEquals(EventoTipo expected, EventoTipo actual) {
        assertEventoTipoAutoGeneratedPropertiesEquals(expected, actual);
        assertEventoTipoAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEventoTipoAllUpdatablePropertiesEquals(EventoTipo expected, EventoTipo actual) {
        assertEventoTipoUpdatableFieldsEquals(expected, actual);
        assertEventoTipoUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEventoTipoAutoGeneratedPropertiesEquals(EventoTipo expected, EventoTipo actual) {
        assertThat(actual)
            .as("Verify EventoTipo auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEventoTipoUpdatableFieldsEquals(EventoTipo expected, EventoTipo actual) {
        assertThat(actual)
            .as("Verify EventoTipo relevant properties")
            .satisfies(a -> assertThat(a.getNombre()).as("check nombre").isEqualTo(expected.getNombre()))
            .satisfies(a -> assertThat(a.getDescripcion()).as("check descripcion").isEqualTo(expected.getDescripcion()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEventoTipoUpdatableRelationshipsEquals(EventoTipo expected, EventoTipo actual) {
        // empty method
    }
}
